version: '3.9'
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    networks:
      - web

networks:
  web:
    name: selenium
