version: '3.9'

services:
  react_app:
    build:
      context: ./misc
      dockerfile: docker.react.dockerfile
    container_name: react_app
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./misc/package.json:/app/package.json
      - ./src:/app/src
      - ./public:/app/public
      - ./features:/app/features
      - ./misc/node_modules:/app/node_modules
    networks:
      - selenium
networks:
  selenium: 
      external: true